# Generated by Django 5.1.1 on 2024-10-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_registeruser'),
        ('crm_app', '0003_profile'),
    ]

    operations = [
    ]
