# Generated by Django 4.0.5 on 2024-10-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user_role', models.CharField(max_length=255)),
                ('emp_id', models.EmailField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
    ]
