# Generated by Django 4.0.5 on 2024-10-11 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_registeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('job_title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('organisation_name', models.CharField(max_length=255)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to='crm_app.registeruser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to='crm_app.registeruser')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('contact_link', models.URLField(max_length=500)),
                ('remark', models.TextField(blank=True, null=True)),
                ('next_date', models.DateField()),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='crm_app.registeruser')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm_app.contacts')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to='crm_app.registeruser')),
            ],
        ),
    ]
