# Generated by Django 5.1.1 on 2024-10-11 06:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_merge_0002_registeruser_0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningData',
            fields=[
                ('organisation_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('customer_address', models.TextField()),
                ('customer_contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')])),
                ('customer_mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')])),
                ('customer_email', models.EmailField(max_length=254)),
                ('company_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_emp_size', models.IntegerField()),
                ('customer_offering', models.CharField(max_length=30)),
                ('competition_of_AT', models.CharField(max_length=50)),
                ('stock_market_registered', models.CharField(max_length=20)),
                ('influncer', models.BooleanField(default=False)),
                ('decision_maker', models.BooleanField(default=False)),
                ('IT_spending_budget', models.CharField(max_length=30)),
                ('source_of_data_mining', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.CharField(default='MP', max_length=50)),
                ('city', models.CharField(default='Indore', max_length=50)),
                ('region', models.CharField(default='North', max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.registeruser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mining_data', to='crm_app.registeruser')),
            ],
        ),
    ]
