# Generated by Django 4.0.5 on 2024-10-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_alter_contacts_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='contact_link',
            field=models.CharField(max_length=500),
        ),
    ]
