# Generated by Django 4.0.5 on 2024-10-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_opportunities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('valid_until', models.DateField()),
                ('approval_status', models.CharField(max_length=50)),
                ('quote_stage', models.CharField(max_length=50)),
                ('invoice_status', models.CharField(max_length=50)),
                ('approval_issue_description', models.TextField(blank=True, null=True)),
                ('account', models.CharField(max_length=255)),
                ('lead_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm_app.leads')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm_app.opportunities')),
            ],
        ),
    ]
