# Generated by Django 4.0.5 on 2024-10-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meet_links', models.URLField(blank=True, max_length=500, null=True)),
                ('task', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='crm_app.contacts')),
            ],
        ),
    ]
