# Generated by Django 5.1.1 on 2024-10-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_miningdata'),
        ('crm_app', '0011_calendar'),
    ]

    operations = [
    ]
