# Generated by Django 5.1.1 on 2024-10-21 07:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_merge_0005_miningdata_0011_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningdata',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.registeruser'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='emp_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quote_number', models.CharField(max_length=50)),
                ('quote_stage', models.CharField(max_length=50)),
                ('valid_until', models.DateField()),
                ('invoice_status', models.CharField(max_length=50)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(max_length=50)),
                ('approval_issue', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.registeruser')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='crm_app.opportunities')),
            ],
        ),
    ]
