# Generated by Django 5.1.2 on 2024-10-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_hr_company_hr_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr_department',
            name='company',
        ),
        migrations.AlterField(
            model_name='employment',
            name='internal_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.department'),
        ),
        migrations.AlterField(
            model_name='hr_employee',
            name='internal_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.department'),
        ),
        migrations.DeleteModel(
            name='HR_Company',
        ),
        migrations.DeleteModel(
            name='HR_Department',
        ),
    ]
