# Generated by Django 5.1.2 on 2024-10-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_terminationreason_terminationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='manual_pay_grade',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='manual_salary_step',
        ),
    ]
