# Generated by Django 4.2.16 on 2024-10-30 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_terminationreason_terminationtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_review_id', models.CharField(max_length=25)),
                ('manager_party_id', models.CharField(max_length=25)),
                ('manager_role_type_id', models.CharField(max_length=25)),
                ('from_date', models.DateField(auto_now_add=True)),
                ('through_date', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('hr_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='crm_app.hr_employee')),
            ],
        ),
    ]
