# Generated by Django 5.1.2 on 2024-11-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_skilltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltype',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
