# Generated by Django 5.1.2 on 2024-11-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_remove_employment_manual_pay_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('has_table', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_positions', to='crm_app.positiontype')),
            ],
            options={
                'verbose_name': 'Position Type',
                'verbose_name_plural': 'Position Types',
            },
        ),
    ]
