# Generated by Django 4.2.16 on 2024-10-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_performancereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('HTML/FTL', 'HTML/FTL'), ('Java/Groovy/BSH', 'Java/Groovy/BSH'), ('JavaScript/Dojo', 'JavaScript/Dojo'), ('Mini Language', 'Mini Language'), ('Not Applicable', 'Not Applicable'), ('OFBiz Installation', 'OFBiz Installation'), ('Screen/Forms', 'Screen/Forms')], max_length=255)),
                ('ofbiz_installation', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('skill_level', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('hr_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_skills', to='crm_app.hr_employee')),
            ],
        ),
    ]
