# Generated by Django 5.1.2 on 2024-11-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_positiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('budget_id', models.CharField(max_length=50)),
                ('budget_item_sequence_id', models.CharField(max_length=50)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('salary_flag', models.BooleanField(default=False)),
                ('tax_exempt_flag', models.BooleanField(default=False)),
                ('full_time_flag', models.BooleanField(default=False)),
                ('temporary_flag', models.BooleanField(default=False)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_finish_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='crm_app.hr_employee')),
                ('employee_position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='crm_app.positiontype')),
                ('internal_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='crm_app.hr_department')),
            ],
        ),
    ]
