# Generated by Django 5.1.2 on 2024-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_alter_skilltype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='skillTypeId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
