# Generated by Django 4.2.16 on 2024-11-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_partyskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyskill',
            name='ofbiz_installation',
        ),
    ]
