# Generated by Django 5.1.2 on 2024-11-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_employeeposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeposition',
            name='budget_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='budget_item_sequence_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='employee_position_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='crm_app.positiontype'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='full_time_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='internal_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='crm_app.hr_department'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='salary_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='tax_exempt_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='temporary_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
