# Generated by Django 4.2.16 on 2024-11-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_remove_employment_manual_pay_grade_and_more'),
        ('crm_app', '0024_alter_partyskill_years_of_experience'),
    ]

    operations = [
    ]
