# Generated by Django 5.1.2 on 2024-11-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_alter_skilltype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltype',
            name='skillTypeId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
