# Generated by Django 4.2.16 on 2024-11-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_merge_20241105_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyskill',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
