# Generated by Django 5.1.2 on 2024-11-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_responsibility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationreason',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
