# Generated by Django 5.1.2 on 2024-11-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0027_alter_employeeposition_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_desc', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('status_id', models.CharField(choices=[('HR_DS_COMPLETE', 'Completed'), ('HR_DS_DEFERRED', 'Deferred'), ('HR_DS_INCOMPLETE', 'Incomplete')], max_length=20)),
                ('verif_status_id', models.CharField(choices=[('PQV_NOT_VERIFIED', 'Not verified'), ('PQV_VERIFIED', 'Verified')], max_length=20)),
                ('thru_date', models.DateField(blank=True, null=True)),
                ('party_qual_type_id', models.CharField(choices=[('BSC', 'Bachelor of Science'), ('B.Tech', 'Bachelor of Technology'), ('CERTIFICATION', 'Certification'), ('DEGREE', 'Degree'), ('MSC', 'Masters of Science'), ('MBA', 'Masters of Business Administration'), ('EXPERIENCE', 'Work Experience')], max_length=20)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='crm_app.hr_employee', to_field='employee_id')),
            ],
        ),
    ]
