# Generated by Django 5.1.2 on 2024-11-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0028_employeequalification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeequalification',
            old_name='thru_date',
            new_name='through_date',
        ),
    ]
