# Generated by Django 5.1.2 on 2024-11-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0029_rename_thru_date_employeequalification_through_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeequalification',
            old_name='verif_status_id',
            new_name='verify_status_id',
        ),
    ]
