# Generated by Django 5.1.2 on 2024-11-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0027_alter_terminationreason_termination_reason'),
        ('crm_app', '0030_rename_verif_status_id_employeequalification_verify_status_id'),
    ]

    operations = [
    ]
