# Generated by Django 5.1.2 on 2024-11-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0031_leavereason_leavetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='leave_Type',
            new_name='leave_type',
        ),
    ]
