# Generated by Django 5.1.2 on 2024-11-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0032_rename_leave_type_leavetype_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('through_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='crm_app.hr_employee', to_field='employee_id')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='crm_app.hr_employee', to_field='employee_id')),
                ('leave_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.leavereason')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.leavetype')),
            ],
        ),
    ]
