# Generated by Django 5.1.2 on 2024-11-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0027_alter_terminationreason_termination_reason'),
        ('crm_app', '0033_employeeleave'),
    ]

    operations = [
    ]
