# Generated by Django 5.1.2 on 2024-11-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0031_merge_20241106_1633'),
        ('crm_app', '0034_merge_20241107_0924'),
    ]

    operations = [
    ]
