# Generated by Django 5.1.2 on 2024-11-07 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0035_employeeleave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(max_length=255)),
                ('content_id', models.CharField(max_length=255)),
                ('resume_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_resumes', to='crm_app.hr_employee', to_field='employee_id')),
            ],
        ),
    ]
