# Generated by Django 4.2.16 on 2024-11-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_alter_partyskill_rating'),
        ('crm_app', '0035_employeeleave_status'),
    ]

    operations = [
    ]
