# Generated by Django 4.2.16 on 2024-11-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0036_merge_20241107_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='manager_role_type_id',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='empl_position_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.positiontype'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='manager_role_type',
            field=models.CharField(choices=[('Account Lead', 'Account Lead'), ('Administrator', 'Administrator'), ('Agent', 'Agent'), ('Automated Agent', 'Automated Agent'), ('Calendar', 'Calendar'), ('Client', 'Client'), ('Communication Participant', 'Communication Participant'), ('Consumer', 'Consumer'), ('Contractor', 'Contractor'), ('Customer', 'Customer'), ('Distribution Channel', 'Distribution Channel'), ('ISP', 'ISP'), ('Hosting Server', 'Hosting Server'), ('Manufacturer', 'Manufacturer'), ('Not Applicable', 'Not Applicable'), ('Organization', 'Organization'), ('Owner', 'Owner'), ('Prospect', 'Prospect')], default='Not Applicable', max_length=255),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='through_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
