# Generated by Django 5.1.2 on 2024-11-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0036_employeeresume'),
        ('crm_app', '0036_merge_20241107_1527'),
    ]

    operations = [
    ]
