# Generated by Django 5.1.2 on 2024-11-08 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0037_merge_0036_employeeresume_0036_merge_20241107_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('job_requisition_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_location', models.CharField(max_length=255)),
                ('job_posting_type', models.CharField(choices=[('JOB_POSTING_EXTR', 'External Job Posting'), ('JOB_POSTING_INTR', 'Internal Job Posting')], max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_resources', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('', 'Not Specified')], default='', max_length=1)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('qualification', models.CharField(choices=[('BSC', 'Bachelor of Science'), ('B.Tech', 'Bachelor of Technology'), ('CERTIFICATION', 'Certification'), ('DEGREE', 'Degree'), ('MSC', 'Masters of Science'), ('MBA', 'Masters of Business Administration'), ('EXPERIENCE', 'Work Experience')], max_length=50)),
                ('exam_type_enum_id', models.CharField(blank=True, choices=[('EXAM_GROUP_DISCN', 'Group Discussion'), ('EXAM_TECHNICAL', 'Technical Exam'), ('EXAM_WRITTEN_APT', 'Written Aptitude Exam')], max_length=50, null=True)),
                ('experience_years', models.PositiveIntegerField()),
                ('experience_months', models.PositiveIntegerField()),
                ('skill_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.skilltype')),
            ],
            options={
                'ordering': ['-job_requisition_id'],
            },
        ),
    ]
