# Generated by Django 4.2.16 on 2024-11-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0037_remove_performancereview_manager_role_type_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancereview',
            old_name='hr_employee',
            new_name='emp_party_id',
        ),
    ]
