# Generated by Django 4.2.16 on 2024-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0038_rename_hr_employee_performancereview_emp_party_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
