# Generated by Django 5.1.2 on 2024-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0039_internaljobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaljobposting',
            name='applicationDate',
            field=models.DateField(),
        ),
    ]
