# Generated by Django 5.1.2 on 2024-11-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0038_jobrequisition'),
        ('crm_app', '0039_paygrade_comments_paygrade_paygradeid_and_more'),
    ]

    operations = [
    ]
