# Generated by Django 4.2.16 on 2024-11-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0039_alter_performancereview_from_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Active/Open'), (2, 'Inactive/Closed'), (3, 'Planned For')], default=1)),
                ('source', models.IntegerField(choices=[(1, 'Advertisement'), (2, 'Job Portal'), (3, 'Internet'), (4, 'News Paper'), (5, 'Personal Referral')], default=1)),
                ('application_date', models.DateField()),
                ('applying_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.hr_employee')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.positiontype')),
            ],
        ),
    ]
