# Generated by Django 4.2.16 on 2024-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0040_employmentapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentapplication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='id',
        ),
        migrations.AlterField(
            model_name='employmentapplication',
            name='application_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='perf_review_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
