# Generated by Django 5.1.2 on 2024-11-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0044_publicholiday_trainingclasstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('trainingClassId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fromDate', models.DateField()),
                ('fromTime', models.TimeField()),
                ('throughDate', models.DateField()),
                ('throughTime', models.TimeField()),
                ('approverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.hr_employee', to_field='employee_id', verbose_name='Approver Party Id')),
                ('trainingType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.trainingclasstype', to_field='tranningTypeId', verbose_name='Training Name')),
            ],
        ),
    ]
