# Generated by Django 5.1.2 on 2024-11-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0044_publicholiday_trainingclasstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygrade',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paygrade',
            name='payGradeId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paygrade',
            name='grade_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
