# Generated by Django 4.2.16 on 2024-11-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0041_remove_employmentapplication_id_and_more'),
        ('crm_app', '0044_publicholiday_trainingclasstype'),
    ]

    operations = [
    ]
