# Generated by Django 5.1.2 on 2024-11-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0045_trainingclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAttendee',
            fields=[
                ('attendeeId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='Assigned', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.hr_employee', to_field='employee_id', verbose_name='Employee Party ID')),
                ('trainingClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.trainingclass', verbose_name='Training Class ID')),
            ],
        ),
    ]
