# Generated by Django 4.2.16 on 2024-11-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0045_merge_20241113_1104'),
        ('crm_app', '0045_paygrade_comments_paygrade_paygradeid_and_more'),
    ]

    operations = [
    ]
