# Generated by Django 4.2.16 on 2024-11-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0046_merge_20241113_1718'),
        ('crm_app', '0046_trainingattendee'),
    ]

    operations = [
    ]
