# Generated by Django 5.1.2 on 2024-11-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0045_paygrade_comments_paygrade_paygradeid_and_more'),
        ('crm_app', '0046_trainingattendee'),
    ]

    operations = [
    ]
