# Generated by Django 5.1.2 on 2024-11-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0047_merge_20241114_1458'),
        ('crm_app', '0047_merge_20241114_1535'),
    ]

    operations = [
    ]
