# Generated by Django 4.2.16 on 2024-11-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0047_merge_0046_merge_20241113_1718_0046_trainingattendee'),
        ('crm_app', '0047_merge_20241114_1458'),
        ('crm_app', '0047_merge_20241114_1535'),
    ]

    operations = [
    ]
