# Generated by Django 4.2.16 on 2024-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0048_merge_20241114_1727'),
        ('crm_app', '0048_merge_20241115_0931'),
    ]

    operations = [
    ]
