# Generated by Django 5.1.2 on 2024-11-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0048_merge_20241114_1727'),
        ('crm_app', '0048_merge_20241115_0931'),
    ]

    operations = [
    ]
