# Generated by Django 5.1.2 on 2024-11-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0049_merge_20241118_0950'),
        ('crm_app', '0049_merge_20241118_1016'),
    ]

    operations = [
    ]
