# Generated by Django 5.1.2 on 2024-11-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0049_merge_20241115_1548'),
        ('crm_app', '0050_merge_20241120_1104'),
        ('crm_app', '0051_payslip'),
    ]

    operations = [
    ]
